= Kakoune Configuration
Parasrah <github@parasrah.com>

== Register Map

Used to document what registers I try to associate with what actions

* `p`                 - clipboard register
* `h`,`j`,`k`,`l`     - user
* `a`,`s`,`d`,`f`     - marks
* `^`,`x`,`z`         - selections
* `@`,`q`,`w`,`e`,`r` - macros
* `/`,`m`,`n`         - search
* `|`                 - pipe
* `1-9`               - regex matches

== Reserved keys

Some keys I want to preserve for future use

* `<c-h,j,k,l>`, `<a-h,j,k,l>` - for when kakoune supports ambiguous keys
** `j,k` keys for jumps inside buffer
** `h,l` keys for jumps across buffers
* `<c-space>` - for explicit lsp completion
* `<c-n>` - for something with normal mode navigation forward, not backward

== Dependencies

rg:: ripgrep, a faster grep alternative
file:: utility to determine file type
jq:: allows parsing json
git:: version control
i3:: window manager
sd:: faster sed replacement
dirname:: used to extract directory name from path
editorconfig-core-c:: used to load editorconfig settings
bc:: math
emmet-cli:: emmet cli wrapper
kitty:: terminal emulator
nnn:: terminal file manager

== Future Features

=== Fallback window management

Would like kakoune to fallback to using kitty for windowing. This would be
useful for environments like chromebooks or remote machines where i3 isn't
available, without impacting my developer experience w/ i3 available

* [ ] create a kitty config that uses the same keys as my i3 config
* [ ] create kitty versions of i3 commands (i3-new-down, etc)
* [ ] create aliases that point to i3 commands if i3wm is running, else kitty
* [ ] use said aliases everywhere in config

=== "IDE" experience

It should be possible to:

1) setup command to open nnn left, new kakoune client below (make buffer?)
2) name original client 'main', bottom client 'tools'
3) set 'main' as jumpclient, 'tools' as toolsclient

=== Auto-Pairs

Want a plugin that

1) only inserts pairs when I actually want pairs to be inserted
2) still works properly with `.` operator

If coming up w/ pure `kakscript` solution to this is not sufficient,
maybe `tree-sitter` could help (and for elixir could just use the
languages macro system to get the AST)
