= Kakoune Configuration
Parasrah <github@parasrah.com>

== Register Map

Used to document what registers I try to associate with what actions

* `p`                 - clipboard register
* `h`,`j`,`k`,`l`     - user
* `a`,`s`,`d`,`f`     - marks
* `^`,`x`,`z`         - selections
* `@`,`q`,`w`,`e`,`r` - macros
* `/`,`m`,`n`         - search
* `|`                 - pipe
* `1-9`               - regex matches

== Reserved keys

Some keys I want to preserve for future use

* `<c-h,j,k,l>`, `<a-h,j,k,l>` - for when kakoune supports ambiguous keys
** `j,k` keys for jumps inside buffer
** `h,l` keys for jumps across buffers
* `<c-space>` - for explicit lsp completion
* `<c-n>` - for something with normal mode navigation forward, not backward

== Dependencies

rg:: ripgrep, a faster grep alternative
file:: utility to determine file type
jq:: allows parsing json
git:: version control
i3:: window manager
dirname:: used to extract directory name from path
editorconfig-core-c:: used to load editorconfig settings
bc:: math
httpie:: curl replacement
emmet-cli:: emmet cli wrapper
kitty:: terminal emulator
nnn:: terminal file manager
